### ISSUE TITLE
Can't import Zyklus for website using Vite (TypeScript + Vite)

### ISSUE THREAD

**Issue by Bubobubobubobubo** [felixroos/zyklus#1]
Hi, 

As discussed earlier on Discord, it is currently impossible to import `Zyklus` on a TypeScript website made with Vite. The error seems to appear during bundling:

```typescript
[plugin:vite:import-analysis] Failed to resolve entry for package "zyklus". The package may have incorrect main/module/exports specified in its package.json.
```

In the meantime, I have copied the package code in my application and will fall back to the package once resolved.

**Comment by felixroos** [comment]
fixed! was just a typo in the package.json see https://github.com/felixroos/zyklus/commit/91f4c6839b1198326361ee59fd7df8e1a1349674
